apiVersion: v1
kind: Service
metadata:
  name: faster-whisper-server
  namespace: whisper
spec:
  selector:
    app: faster-whisper-server
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30800
  type: NodePort
